apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatbot-training
  namespace: chatbot
  labels:
    app: chatbot-training
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chatbot-training
  template:
    metadata:
      labels:
        app: chatbot-training
    spec:
      containers:
        - name: chatbot-training
          image: docker.io/umesh1212/chatbot-traininig:v3
          ports:
            - containerPort: 80
          env:
            - name: GEMINI_API_KEY
              value: "fake_AIzaSyD0AJenwJk-GKJhTThHHmi8BTrZ-bd6jT0"
            - name: QDRANT_URL
              value: "https://qdrant.do.umeshkhatiwada.com.np:443"
            - name: APIKEY
              value: "fake_fkjabjkbsajkbasjkdbaksjbdkabdkjbadkjbadbauosdib"
            - name: COLLECTION_NAME
              value: "chatbot-docs"
            - name: AI_MODEL
              value: "gemini-2.5-pro"
            - name: TEXT_EMBED
              value: "text-embedding-005"
            - name: APP_TITLE
              value: "🤖 Chatbot"
            - name: APP_CONTENT
              value: "Welcome! How can I help you?"
            - name: RABBITMQ_URL
              value: "amqps://fake:jnb7-OO-L-PhHvC9S8XbhuKKgZsfMI6R@fuji.lmq.cloudamqp.com/reyvuxdc"
            - name: QUEUE_NAME
              value: "test1"
            - name: DOCS_ROOT_DIR
              value: "./chatbot-docs/content"
          resources:
            limits:
              memory: "100Mi"
              cpu: "100m"
            requests:
              memory: "25Mi"
              cpu: "25m"
---
apiVersion: v1
kind: Service
metadata:
  name: chatbot-training
  namespace: chatbot
spec:
  selector:
    app: chatbot-training
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP